title: Cristian Rivera | Portafolio de Analista de Datos
description: Analista de Datos especializado en Power BI, SQL, Excel y Python. Explora proyectos enfocados en inteligencia de negocios, visualización de datos y análisis.
theme: jekyll-theme-minimal
